# Generated by Django 5.1 on 2024-08-13 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FedoraCoffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'In Progress'), (2, 'Paying'), (3, 'Done')], default=1)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='FedoraCoffee.client')),
            ],
        ),
    ]
